services:
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: questoes_enem_dev
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  next-app-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    ports:
      - '3000:3000'
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    env_file:
      - .env

volumes:
  postgres_data:
