# Use a specific Node.js version
FROM node:lts-alpine3.21

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json to leverage Docker cache
COPY package*.json ./

# Install all dependencies, including devDependencies
RUN npm install

# Copy the rest of the application's source code
COPY . .

# Expose the port the app runs on
EXPOSE 3000

# Start the app in development mode with hot-reloading
CMD sh -c "npx prisma db push && npm run dev"
